Add Board and User admin details view
marmelab/labyrinth pull request #40
Opened 2023-03-15 16:32 UTC by jonathan-marmelab

This closes the following user story: https://trello.com/c/dAMqJonv/44-2-as-robert-i-want-to-be-able-to-see-all-games-and-be-able-to-delete-some-5

![Peek 15-03-2023 17-31](https://user-images.githubusercontent.com/125876152/225377205-69357b68-cf37-488d-a0c8-1f48277a7bd1.gif)

2023-03-15 17:34 UTC, JulienMattiussi requested changes
Can you give instructions in readme on how to login in admin locally ?
what acount for example or how to create it ?

2023-03-15 17:34 UTC, JulienMattiussi commented on admin/src/board/commons.ts
> +  switch (game_state) {
can you use named states for these values to avoid magical numbers ?

2023-03-16 08:54 UTC, fzaninotto commented on admin/src/board/commons.ts
> +  switch (game_state) {
Can you extract the case and return to an object? You'll reduce the complexityn get rid of the switch statement, and surface an important piece of data.

2023-03-16 09:35 UTC, JulienMattiussi approved these changes

2023-03-16 09:40 UTC, merged