Add integration tests
marmelab/labyrinth pull request #42
Opened 2023-03-16 11:10 UTC by jonathan-marmelab

2023-03-16 14:57 UTC, fzaninotto commented on .github/workflows/ci-cd.yml
> +      - name: Run Cypress tests
nice, but your pipeline is called `unit-tests`... You should maybe rename it now that it also does e2e tests.

2023-03-16 15:48 UTC, JulienMattiussi requested changes

2023-03-16 15:48 UTC, JulienMattiussi commented on cypress/e2e/admin/login.cy.js
> +describe('Admin Login', () => {
it can be the correct moment to start implementing PageObjects in tests
ask François about priority about this
if not, these tests are nice

2023-03-16 15:48 UTC, JulienMattiussi commented on README.md
> +To run nd-to-End tests, you will need to install Cypress dependencies, please see the [system requirements](https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements).
little typo on nd-to-End

2023-03-16 15:48 UTC, JulienMattiussi commented on webapp/migrations/Dockerfile
> +ENTRYPOINT [ "./run-migrations.sh" ]
not that important but don't you have a linting issue with last line of files ?

2023-03-17 07:56 UTC, JulienMattiussi approved these changes

2023-03-17 09:14 UTC, JulienMattiussi commented on cypress/e2e/admin/login.cy.js
> +        const adminSignInPage = new AdminSignIn();
you should use a beforeEach to avoid repeating `new AdminSignIn()`in each test

2023-03-17 09:18 UTC, merged